-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 12:56:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema meals_on_wheels
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meals_on_wheels
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meals_on_wheels` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `meals_on_wheels` ;

-- -----------------------------------------------------
-- Table `meals_on_wheels`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`admin` (
  `ad_id` INT NOT NULL,
  `name` INT NOT NULL,
  PRIMARY KEY (`ad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`caregiver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`caregiver` (
  `cg_id` INT NOT NULL,
  `name` INT NOT NULL,
  `contact` INT NOT NULL,
  `address` INT NOT NULL,
  PRIMARY KEY (`cg_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`donator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`donator` (
  `d_id` INT NOT NULL,
  `contact` INT NOT NULL,
  `address` INT NOT NULL,
  `name` INT NOT NULL,
  PRIMARY KEY (`d_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`funds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`funds` (
  `f_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `date` INT NOT NULL,
  `d_id` INT NOT NULL,
  `ad_id` INT NOT NULL,
  PRIMARY KEY (`f_id`),
  INDEX `d_id` (`d_id` ASC) VISIBLE,
  INDEX `ad_id` (`ad_id` ASC) VISIBLE,
  CONSTRAINT `funds_ibfk_1`
    FOREIGN KEY (`d_id`)
    REFERENCES `meals_on_wheels`.`donator` (`d_id`),
  CONSTRAINT `funds_ibfk_2`
    FOREIGN KEY (`ad_id`)
    REFERENCES `meals_on_wheels`.`admin` (`ad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`member` (
  `mem_id` INT NOT NULL,
  `name` INT NOT NULL,
  `address` INT NOT NULL,
  `health_issue` INT NOT NULL,
  `contact` INT NOT NULL,
  PRIMARY KEY (`mem_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`partner` (
  `p_id` INT NOT NULL,
  `name` INT NOT NULL,
  `address` INT NOT NULL,
  `contact` INT NOT NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`menu` (
  `ml_id` INT NOT NULL,
  `meal_details` INT NOT NULL,
  `nutrition_info` INT NOT NULL,
  `ingredients` INT NOT NULL,
  `p_id` INT NOT NULL,
  PRIMARY KEY (`ml_id`),
  INDEX `p_id` (`p_id` ASC) VISIBLE,
  CONSTRAINT `menu_ibfk_1`
    FOREIGN KEY (`p_id`)
    REFERENCES `meals_on_wheels`.`partner` (`p_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`volunteer` (
  `v_id` INT NOT NULL,
  `name` INT NOT NULL,
  `address` INT NOT NULL,
  `contact` INT NOT NULL,
  PRIMARY KEY (`v_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `meals_on_wheels`.`meal_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meals_on_wheels`.`meal_order` (
  `o_id` INT NOT NULL,
  `date` INT NOT NULL,
  `mem_id` INT NOT NULL,
  `cg_id` INT NOT NULL,
  `ml_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  `v_id` INT NOT NULL,
  `ad_id` INT NOT NULL,
  PRIMARY KEY (`o_id`),
  INDEX `mem_id` (`mem_id` ASC) VISIBLE,
  INDEX `cg_id` (`cg_id` ASC) VISIBLE,
  INDEX `ml_id` (`ml_id` ASC) VISIBLE,
  INDEX `p_id` (`p_id` ASC) VISIBLE,
  INDEX `v_id` (`v_id` ASC) VISIBLE,
  INDEX `ad_id` (`ad_id` ASC) VISIBLE,
  CONSTRAINT `meal_order_ibfk_1`
    FOREIGN KEY (`mem_id`)
    REFERENCES `meals_on_wheels`.`member` (`mem_id`),
  CONSTRAINT `meal_order_ibfk_2`
    FOREIGN KEY (`cg_id`)
    REFERENCES `meals_on_wheels`.`caregiver` (`cg_id`),
  CONSTRAINT `meal_order_ibfk_3`
    FOREIGN KEY (`ml_id`)
    REFERENCES `meals_on_wheels`.`menu` (`ml_id`),
  CONSTRAINT `meal_order_ibfk_4`
    FOREIGN KEY (`p_id`)
    REFERENCES `meals_on_wheels`.`partner` (`p_id`),
  CONSTRAINT `meal_order_ibfk_5`
    FOREIGN KEY (`v_id`)
    REFERENCES `meals_on_wheels`.`volunteer` (`v_id`),
  CONSTRAINT `meal_order_ibfk_6`
    FOREIGN KEY (`ad_id`)
    REFERENCES `meals_on_wheels`.`admin` (`ad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
