server:
  port: 8546

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://100.110.13.2:3306/deez_nutz
    username: yeems214
    password: roelfrancis100
  jpa:
    hibernate:
      ddl-auto: create